spring:
  application:
    name: cinema
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
